import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import path from 'node:path';
import type { Result, ProjectMap, DependencyGraph } from '../types/index.js';
import { ok, err, toOS, logger } from '../utils/index.js';
import type { Convention } from '../types/index.js';

const CLAUDE_OPT_START_MARKER = '<!-- claude-opt:start -->';
const CLAUDE_OPT_END_MARKER = '<!-- claude-opt:end -->';

// ─── Convention detection ─────────────────────────────────────

const NAMING_PATTERNS: Record<string, RegExp> = {
  'kebab-case': /^[a-z][a-z0-9]*(-[a-z0-9]+)*$/,
  camelCase: /^[a-z][a-zA-Z0-9]*$/,
  PascalCase: /^[A-Z][a-zA-Z0-9]*$/,
  snake_case: /^[a-z][a-z0-9]*(_[a-z0-9]+)*$/,
};

export function detectConventions(projectMap: ProjectMap): Convention[] {
  const conventions: Convention[] = [];
  const files = Object.keys(projectMap.files);

  // ── File naming convention ──
  const namingCounts: Record<string, number> = {};
  let totalNamed = 0;

  for (const filePath of files) {
    const baseName = path.basename(filePath, path.extname(filePath));
    if (baseName === 'index' || baseName.includes('.test') || baseName.includes('.spec')) continue;
    totalNamed++;

    for (const [pattern, regex] of Object.entries(NAMING_PATTERNS)) {
      if (regex.test(baseName)) {
        namingCounts[pattern] = (namingCounts[pattern] ?? 0) + 1;
      }
    }
  }

  if (totalNamed > 0) {
    const sorted = Object.entries(namingCounts).sort((a, b) => b[1] - a[1]);
    if (sorted.length > 0) {
      const [topPattern, topCount] = sorted[0];
      const confidence = topCount / totalNamed;
      if (confidence > 0.3) {
        conventions.push({
          pattern: `File naming: ${topPattern}`,
          description: `Files primarily use ${topPattern} naming`,
          examples: files
            .filter((f) => NAMING_PATTERNS[topPattern].test(path.basename(f, path.extname(f))))
            .slice(0, 3),
        });
      }
    }
  }

  // ── Test file patterns ──
  const hasColocated = files.some((f) => f.includes('.test.') || f.includes('.spec.'));
  const hasSeparateTests = files.some((f) => f.startsWith('tests/') || f.startsWith('test/') || f.includes('__tests__/'));

  if (hasColocated && hasSeparateTests) {
    conventions.push({
      pattern: 'Test files: mixed (co-located + separate dir)',
      description: 'Tests use both co-located files and a separate tests directory',
      examples: [],
    });
  } else if (hasSeparateTests) {
    conventions.push({
      pattern: 'Test files: separate directory',
      description: 'Tests are organized in a dedicated tests directory',
      examples: files.filter((f) => f.startsWith('tests/') || f.startsWith('test/')).slice(0, 3),
    });
  } else if (hasColocated) {
    conventions.push({
      pattern: 'Test files: co-located',
      description: 'Test files are co-located alongside source files',
      examples: files.filter((f) => f.includes('.test.') || f.includes('.spec.')).slice(0, 3),
    });
  }

  // ── Source directory ──
  const srcDirs = ['src/', 'lib/', 'app/'];
  for (const dir of srcDirs) {
    if (files.some((f) => f.startsWith(dir))) {
      conventions.push({
        pattern: `Source directory: ${dir.slice(0, -1)}/`,
        description: `Source code is organized under ${dir}`,
        examples: files.filter((f) => f.startsWith(dir)).slice(0, 3),
      });
      break;
    }
  }

  // ── Barrel exports ──
  const indexFiles = files.filter((f) => path.basename(f).startsWith('index.'));
  if (indexFiles.length > 1) {
    conventions.push({
      pattern: 'Barrel exports: index files',
      description: 'Directories use index files as barrel exports',
      examples: indexFiles.slice(0, 3),
    });
  }

  // ── Package manager ──
  const lockFiles: Record<string, string> = {
    'package-lock.json': 'npm',
    'yarn.lock': 'yarn',
    'pnpm-lock.yaml': 'pnpm',
    'bun.lockb': 'bun',
  };
  for (const [lockFile, manager] of Object.entries(lockFiles)) {
    if (files.includes(lockFile)) {
      conventions.push({
        pattern: `Package manager: ${manager}`,
        description: `Project uses ${manager} as package manager`,
        examples: [lockFile],
      });
      break;
    }
  }

  return conventions;
}

// ─── CLAUDE.md content building ───────────────────────────────

function buildClaudeMdContent(
  projectMap: ProjectMap,
  depGraph: DependencyGraph,
  conventions: Convention[],
): string {
  const lines: string[] = [];

  lines.push('# Project Context (Auto-generated by claude-opt)');
  lines.push('');
  lines.push(`**Project Type:** ${projectMap.projectType}`);
  lines.push(`**Total Files:** ${projectMap.totalFiles}`);
  lines.push(`**Last Scanned:** ${projectMap.scannedAt}`);
  lines.push('');

  // ── Project Structure ──
  lines.push('## Project Structure');
  lines.push('');

  // File type summary
  const typeCounts: Record<string, number> = {};
  for (const entry of Object.values(projectMap.files)) {
    const lang = entry.language ?? 'other';
    typeCounts[lang] = (typeCounts[lang] ?? 0) + 1;
  }
  for (const [type, count] of Object.entries(typeCounts).sort((a, b) => b[1] - a[1])) {
    lines.push(`- ${type}: ${count} files`);
  }
  lines.push('');

  // ── Conventions ──
  if (conventions.length > 0) {
    lines.push('## Detected Conventions');
    lines.push('');
    for (const conv of conventions) {
      lines.push(`- ${conv.pattern}`);
      if (conv.description) lines.push(`  ${conv.description}`);
    }
    lines.push('');
  }

  // ── Key Files ──
  lines.push('## Key Files');
  lines.push('');

  // Entry points
  const entryPoints = Object.keys(projectMap.files).filter(
    (f) => path.basename(f) === 'index.ts' || path.basename(f) === 'index.js' || path.basename(f) === 'main.py',
  );
  if (entryPoints.length > 0) {
    lines.push('**Entry points:**');
    for (const ep of entryPoints.slice(0, 5)) {
      lines.push(`- ${ep}`);
    }
    lines.push('');
  }

  // Config files
  const configFiles = Object.keys(projectMap.files).filter((f) => {
    const base = path.basename(f);
    return (
      base === 'package.json' ||
      base === 'tsconfig.json' ||
      base === 'setup.py' ||
      base.endsWith('.config.ts') ||
      base.endsWith('.config.js')
    );
  });
  if (configFiles.length > 0) {
    lines.push('**Configuration:**');
    for (const cf of configFiles.slice(0, 5)) {
      lines.push(`- ${cf}`);
    }
    lines.push('');
  }

  // Most-imported files (highest in-degree)
  const inDegree: [string, number][] = Object.entries(depGraph.adjacency)
    .map(([file, entry]) => [file, entry.importedBy.length] as [string, number])
    .filter(([, count]) => count > 0)
    .sort((a, b) => b[1] - a[1]);

  if (inDegree.length > 0) {
    lines.push('**Most imported:**');
    for (const [file, count] of inDegree.slice(0, 5)) {
      lines.push(`- ${file} (${count} importers)`);
    }
    lines.push('');
  }

  // ── Domains ──
  if (Object.keys(projectMap.domains).length > 0) {
    lines.push('## Domains');
    lines.push('');
    for (const [domain, files] of Object.entries(projectMap.domains).sort((a, b) => b[1].length - a[1].length)) {
      lines.push(`- **${domain}**: ${files.length} files`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

// ─── CLAUDE.md content preservation ───────────────────────────

function updateClaudeMdContent(existingContent: string, generatedContent: string): string {
  const wrappedContent = `${CLAUDE_OPT_START_MARKER}\n${generatedContent}\n${CLAUDE_OPT_END_MARKER}`;

  const startIdx = existingContent.indexOf(CLAUDE_OPT_START_MARKER);
  const endIdx = existingContent.indexOf(CLAUDE_OPT_END_MARKER);

  if (startIdx !== -1 && endIdx !== -1) {
    // Replace content between markers
    return (
      existingContent.slice(0, startIdx) +
      wrappedContent +
      existingContent.slice(endIdx + CLAUDE_OPT_END_MARKER.length)
    );
  }

  // Append to end
  return existingContent.trimEnd() + '\n\n' + wrappedContent + '\n';
}

// ─── Public API ───────────────────────────────────────────────

export function generateClaudeMd(
  projectRoot: string,
  projectMap: ProjectMap,
  depGraph: DependencyGraph,
): Result<void> {
  const conventions = detectConventions(projectMap);
  const generatedContent = buildClaudeMdContent(projectMap, depGraph, conventions);

  const claudeMdPath = path.join(toOS(projectRoot), 'CLAUDE.md');

  let finalContent: string;
  if (existsSync(claudeMdPath)) {
    try {
      const existingContent = readFileSync(claudeMdPath, 'utf-8');
      finalContent = updateClaudeMdContent(existingContent, generatedContent);
    } catch (e) {
      return err(`Failed to read existing CLAUDE.md: ${String(e)}`);
    }
  } else {
    finalContent = `${CLAUDE_OPT_START_MARKER}\n${generatedContent}\n${CLAUDE_OPT_END_MARKER}\n`;
  }

  try {
    writeFileSync(claudeMdPath, finalContent, 'utf-8');
  } catch (e) {
    return err(`Failed to write CLAUDE.md: ${String(e)}`);
  }

  logger.info('claudemd', `Generated CLAUDE.md (${conventions.length} conventions detected)`);
  return ok(undefined);
}
